name: hackers-plugin
version: "1.0-SNAPSHOT"
author: Zdenek Nemec
main: cz.artin.hackers.HackersPlugin
commands:
  createPlain:
    description: Creates a plain
  createPool:
    description: Creates a pool beneath the player
  setCasual:
    description: Sets casual environment
  setNighmare:
    description: Sets nightmarish environment
  spawnChickens:
    description: Spawns a group of chickens
  spawnZombie:
    description: Spawns a zombie
  house:
    description: Builds a house around the player
