name: hackers-plugin
version: "1.0-SNAPSHOT"
author: xvojta
main: cz.artin.hackers.HackersPlugin

commands:
  zombie:
    description: Spawns a zombie
  chicken:
    description: Spawns a chicken
  house:
    description: Build a house
  gun:
    description: Give gun