name: hackers-plugin
version: "1.0-SNAPSHOT"
author: Zdenek Nemec
main: cz.artin.hackers.HackersPlugin
commands:
  zombie:
    description: Spawns a zombie
  chickens:
    description: Spawns a group of chickens
  water:
    descriprion: Changes block under the player into a water
