name: hackers-plugin
version: "1.0-SNAPSHOT"
author: Artin Hacker
main: cz.artin.hackers.HackersPlugin

commands:
  zombie:
    description: Spawn a zombie near wiev
  chicken:
    description: Gets you a perfect meal
  firewand:
    description: Gets you a fire wand
  snowwand:
    description: Gets you a ice wand
  house:
    description: Build house