name: hackers-plugin
version: "1.0-SNAPSHOT"
author: Zdenek Nemec
main: cz.artin.hackers.HackersPlugin
commands:
  createPool:
    description: Creates a pool beneath the player
  spawnChickens:
    description: Spawns a group of chickens
  spawnZombie:
    description: Spawns a zombie
  house:
    description: Builds a house around the player
  day:
    description: Sets day-time
  plain:
    description: Creates a plain
