name: hackers-plugin
version: "1.0-SNAPSHOT"
author: Filip Bartl
main: cz.artin.hackers.HackersPlugin
commands:
  kure:
    description: vytvor kure
  vlk:
    description: Vytvor vlka
  kralik:
    description: vytvor kralika
  zombie:
    description: vytvor zombika
  spider:
    description: vytvor pavouka
  most:
    description: postavit most
  strecha:
    description: Vytvor strechu
  zed2:
    description: vytvor zed2
  zed:
    description: vytvor zed
  cistic:
    description: udelej cisto
  strecha1:
    description: vytvor strechu
  dum:
    description: vytvor dum
  bazen:
    description: udelej podlahu
  rybnik:
    description: udelej rybnik
  most2:
    description: udelej most2
  ohrada:
    description: vytvor ohradu
  magickasekera:
    description: vytvor magickousekeru
  magickykrumpac:
    description: vytvor magickykrumpac
  magickymec:
    description: vytvor magickymec
  magickysip:
    description: vytvor magickysip
  magickydiamantovymec:
    description: vytvor magickydiamantovymec
  magickalopata:
    description: vytvor magickoulopatu
  nicicilopata:
    description: vytvor nicicilopatu
  supermec:
    description: vytvor supermec
  zlatykrumpac:
    description: vytvor zlatykrumpac
  teleport2:
    description: teleportuj hrace do mesta
  teleport:
    description: teleportuje hrace do mesta
  teleportovatnazacatek:
    description: teleportuj na zacatek
  portal:
    description: vytvor portal

