name: hackers-plugin
version: "1.0-SNAPSHOT"
author: Filip Bartl
main: cz.artin.hackers.HackersPlugin
commands:
  kure:
    description: vytvor kure
  vlk:
    description: Vytvor vlka
  zed:
    description: postavit zed
  strecha:
    description: Vytvor strechu




